name       : replaysorcery
version    : 0.6.0
release    : 1
source     :
    - git|https://github.com/matanui159/ReplaySorcery.git : 0.6.0
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : An open-source, instant-replay solution for Linux
description: |
    An open-source, instant-replay solution for Linux
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(libdrm)
    - pkgconfig(libpulse)
    - pkgconfig(x11)
    - pkgconfig(xcb)
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-use-CMAKE_INSTALL_PREFIX-for-config-path.patch
    %cmake
build      : |
    %make
install    : |
    %make_install
